### ISSUE TITLE
If you don't have installed Courier font, plugin will not work.

### ISSUE THREAD

**Issue by itsxales** [bryanberger/figma-skeleton-generator#6]
If you don't have on your disc installed Courier font, plugin will not generate skeleton.

![image](https://user-images.githubusercontent.com/53447341/135505294-733cc0ed-dd52-4a80-92be-560ba96cf5ba.png)

After install plugin works fine.

**Comment by bryanberger** [comment]
@itsxales ah, nice catch I thought Courier was preinstalled on macOS/Windows but it's actually `Courier New`
